networks:
  otel_internal-network:
    driver: bridge


services:
  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./product-service/data.json:/product-service/data.json
    env_file:
       - .env
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
      - PRODUCT_DATA_FILE_PATH=/product-service/data.json

    networks:
      - otel_internal-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

    
  product-simulator:
    build:
      context: ./simulations
      dockerfile: Dockerfile
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8082
    networks:
      - otel_internal-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
      - "55679:55679"
    networks:
      - otel_internal-network
    environment:
      - OTEL_RESOURCE_HOST_NAME=${OTEL_RESOURCE_HOST_NAME}
      - SIGNOZ_ENDPOINT=${SIGNOZ_ENDPOINT}
      - SIGNOZ_INGESTION_KEY=${SIGNOZ_INGESTION_KEY}


































  