networks:
  otel_internal-network:
    driver: bridge


services:
  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    container_name: product-service
    ports:
      - 8082:8082
    volumes:
      - ./product-service/data.json:/app/data.json:ro
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/v1/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - otel_internal-network
    depends_on:
      otel-collector:
        condition: service_started
  product-simulator:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      product-service:
        condition: service_healthy

    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8082/api/v1
    networks:
      - otel_internal-network



  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    user: "0"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 4317:4317
      - 4318:4318


    networks:
      - otel_internal-network
































  