networks:
  otel_internal-network:
    driver: bridge


services:    
  product-simulator:
    container_name: simulator-service
    build:
      context: ./locust-simulations
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - PRODUCT_SERVICE_URL=http://nginx:80
      - LOAD_SHAPE=stages
      - OTEL_ENDPOINT=otel-collector:4317
      - OTEL_ENABLED=false
      - SERVICE_NAME=product-simulator
    networks:
      - otel_internal-network
    depends_on:
      - nginx
    volumes:
      - ./locust-simulations/results:/app/results
    command: ["./scripts/run_tests.sh", "ui", "10", "10", "300", "${PRODUCT_SERVICE_URL}", "stages"]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    container_name: local-otel-collector
    user: "0:0"
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
      - "55679:55679"
    networks:
      - otel_internal-network
    environment:
      - OTEL_RESOURCE_HOST_NAME=${OTEL_RESOURCE_HOST_NAME}
      - SIGNOZ_ENDPOINT=${SIGNOZ_ENDPOINT}
      - SIGNOZ_INGESTION_KEY=${SIGNOZ_INGESTION_KEY}



  product-service-1:
    container_name: ${SERVICE_NAME}-1
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    volumes:
      - ./product-service/data.json:/product-service/data.json
    env_file:
       - .env
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
      - PRODUCT_DATA_FILE_PATH=/product-service/data.json
      - SERVICE_NAME=${SERVICE_NAME}-1
      - SERVICE_VERSION=v5
    networks:
      - otel_internal-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  
  product-service-2:
    container_name: ${SERVICE_NAME}-2
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    volumes:
      - ./product-service/data.json:/product-service/data.json
    env_file:
       - .env
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
      - PRODUCT_DATA_FILE_PATH=/data.json
      - SERVICE_NAME=${SERVICE_NAME}-2
      - SERVICE_VERSION=v5
    networks:
      - otel_internal-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - otel_internal-network
    depends_on:
      - product-service-1
      - product-service-2



































  