networks:
  otel_internal-network:
    driver: bridge


services:
  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    # expose:
    #   - "8082"
    ports:
      - "8082:8082"
    volumes:
      - ./product-service/data.json:/app/data.json
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DATA_FILE_PATH=/app/data.json
      - OTEL_SERVICE_NAME=product-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development,service.version=1.0.0
    networks:
      - otel_internal-network
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.25'
          memory: 32M

    
  product-simulator:
    build:
      context: ./tests
      dockerfile: Dockerfile
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8082
    networks:
      - otel_internal-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
      - "55679:55679"
    networks:
      - otel_internal-network


































  