networks:
  signoz-net:
    driver: bridge
    name: signoz-net
    external: true # Use the existing network created by SigNoz setup
    # Removed external: true - Docker Compose will create this network
    # external: true

services:
  # --- Product Service (Your Application) ---
  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    container_name: product-service
    ports:
      - "8082:8082"
    networks:
      - signoz-net
    # Removed env_file as config is hardcoded in Go
    volumes:
      - ./product-service/data.json:/app/data.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/v1/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # --- Product Simulator Service (Load Generator) ---
  product-simulator:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      product-service:
        condition: service_healthy # Wait for product-service to be healthy
    # Removed env_file, setting URL directly via environment
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8082/api/v1
    networks:
      - signoz-net
    # Removed deploy replicas block - use `docker-compose up --scale product-simulator=N` instead
    # deploy:
    #   replicas: 5

  