networks:
  otel_internal-network:
    driver: bridge


services:
  # --- Product Service (Your Application) ---
  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    container_name: product-service
    ports:
      - 8082:8082
    volumes:
      - ./product-service/data.json:/app/data.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/v1/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - otel_internal-network
    depends_on:
      - otel-collector

  # --- Product Simulator Service (Load Generator) ---
  product-simulator:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      product-service:
        condition: service_healthy # Wait for product-service to be healthy
    # Set the URL for the product-service within the Docker network
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8082/api/v1
    networks:
      - otel_internal-network
    # deploy:
    #   replicas: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317
      - 4318:4318
      # Expose zPages for healthcheck if needed, often on 55679
      # - 55679:55679 
    networks:
      - otel_internal-network


  