# Main application Compose file
networks:
  signoz-net:
    external: true
    name: signoz-net # Must match the name defined in docker-compose.signoz.yml; used for communication with Signoz containers.

services:
  # --- Product Service (Keep our service definition) ---
  product-service:
    build:
      context: . # Build context is the root directory
      dockerfile: ./product-service/Dockerfile
    container_name: product-service # Keeping explicit name for clarity if desired
    ports:
      - "8082:8082" # Map host port to container port
    networks:
      - signoz-net # Connect to the externally defined network
    env_file:
      - .env # Load environment variables (like OTLP endpoint, service name) from .env file
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/v1/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s # Give some time for the service to start initially
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # --- Product Simulator Service (Based on tests/Dockerfile) ---
  product-simulator:
    build:
      context: ./tests # Build context is the tests directory
      dockerfile: Dockerfile
    depends_on:
      - product-service # Ensure product-service starts first
    networks:
      - signoz-net
    deploy:
      replicas: 5 # Specify 5 instances



