# Main application Compose file
version: "3.8"

networks:
  signoz-net:
    driver: bridge
    name: signoz-net

volumes:
  clickhouse_data: {}
  signoz_otel_collector_data: {}

services:
  # --- Product Service (Your Application) ---
  product-service:
    image: local/product-service:latest # Assuming image is built externally (e.g., via ko, Make)
    container_name: product-service
    ports:
      - "8082:8082"
    networks:
      - signoz-net
    env_file:
      - .env # Ensure OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317 (gRPC) is set in .env
    depends_on:
      otel-collector:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/v1/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # --- Product Simulator Service (Load Generator) ---
  product-simulator:
    build:
      context: ./tests
      dockerfile: Dockerfile
    container_name: product-simulator
    depends_on:
      product-service:
        condition: service_healthy # Wait for product-service to be healthy
      otel-collector:
        condition: service_started
    networks:
      - signoz-net
    deploy:
      replicas: 5

  