receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          insecure: true
  docker_stats:
    endpoint: "unix:///var/run/docker.sock"
    collection_interval: 10s
    timeout: 100s
    api_version: "1.47"


processors:
  batch: {}

  resource:
    attributes:
      - key: host.name
        value: "${OTEL_RESOURCE_HOST_NAME}"
        action: update


exporters:
  otlp: 
    endpoint: "${SIGNOZ_ENDPOINT}"
    tls:
      insecure: false
    headers:
      signoz-ingestion-key: "${SIGNOZ_INGESTION_KEY}"
  debug:
    verbosity: detailed

extensions:
  health_check: {}
  pprof: {}
  zpages: {}

service:
  telemetry:
    logs:
      level: "debug"
      encoding: "json"
  # extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource]
      exporters: [otlp]
    metrics:
      receivers: [otlp, docker_stats]
      processors: [resource]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp]




      