receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  docker_stats:
    endpoint: "unix:///var/run/docker.sock"
    collection_interval: 10s
    timeout: 100s
    api_version: "1.47"
  hostmetrics:
    collection_interval: 10s
    root_path: /hostfs
    scrapers:
      cpu:
      memory:
      disk:
      network:
      filesystem:
  nginx:
    endpoint: "http://nginx:80/nginx_status"


processors:
  resourcedetection:
    detectors: [env, docker]
    timeout: 2s
    # override: false # uncomment if you want SDK attributes to always take precedence


exporters:
  otlp: 
    endpoint: "${SIGNOZ_ENDPOINT}"
    tls:
      insecure: false
    headers:
      signoz-ingestion-key: "${SIGNOZ_INGESTION_KEY}"
  debug:
    verbosity: detailed

extensions:
  health_check: {}

service:
  telemetry:
    logs:
      level: "debug"
      encoding: "json"
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection]
      exporters: [otlp]
    metrics:
      receivers: [docker_stats, hostmetrics, nginx, otlp]
      processors: [resourcedetection]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      processors: [resourcedetection]
      exporters: [otlp]




      