receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  # otlp: # Temporarily removed
  #   endpoint: "ingest.in.signoz.cloud:443"
  #   tls:
  #     insecure: false
  #   headers:
  #     signoz-ingestion-key: dtsa409InZNwTUjVBS7WPrNLBsANF1ZnZJXd
  debug:
    verbosity: detailed

extensions:
  health_check: {}
  pprof: {}
  zpages: {}

service:
  telemetry:
    logs:
      level: "DEBUG"
      development: true
      encoding: "json"
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # Only debug exporter
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # Only debug exporter
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # Only debug exporter 



      