receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  docker_stats:
    endpoint: "unix:///var/run/docker.sock"
    collection_interval: 10s
    timeout: 100s
    api_version: "1.47"
  hostmetrics:
    collection_interval: 10s
    root_path: /hostfs
    scrapers:
      cpu:
      memory:
      disk:
      network:
      filesystem:
  nginx:
    endpoint: "http://nginx:80/nginx_status"


processors:
  resource:
    attributes:
      - key: service.name
        value: "${SERVICE_NAME}"
        action: insert
      - key: service.version
        value: "${SERVICE_VERSION}"
        action: insert
      - key: host.name
        value: "narenders-local-host"
        action: update


exporters:
  otlp: 
    endpoint: "${SIGNOZ_ENDPOINT}"
    tls:
      insecure: false
    headers:
      signoz-ingestion-key: "${SIGNOZ_INGESTION_KEY}"
  debug:
    verbosity: detailed

extensions:
  health_check: {}

service:
  telemetry:
    logs:
      level: "debug"
      encoding: "json"
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [resource]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      processors: [resource]
      exporters: [otlp]




      