receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  # docker_stats:
  #   endpoint: "unix:///var/run/docker.sock"
  #   collection_interval: 10s
  #   timeout: 100s
  #   api_version: "1.47"


processors:
  batch: {}

  resourcedetection:
    detectors: [system, docker]
    override: true
  resource:
    attributes:
      - key: host.name
        value: "FIXING_SPANS_1"
        action: upsert


exporters:
  otlp: 
    endpoint: "ingest.in.signoz.cloud:443"
    tls:
      insecure: false
    headers:
      signoz-ingestion-key: dtsa409InZNwTUjVBS7WPrNLBsANF1ZnZJXd
  debug:
    verbosity: detailed

extensions:
  health_check: {}
  pprof: {}
  zpages: {}

service:
  telemetry:
    logs:
      level: "debug"
      encoding: "json"
  # extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, debug]
    # metrics:
    #   receivers: [otlp, docker_stats]
    #   processors: [resourcedetection, resource, batch]
    #   exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch, resourcedetection, resource]
      exporters: [otlp]




      