receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      disk:
      load:
      memory:
      network:
      filesystem:
      paging:
      process:
      processes:

processors:
  batch: {}
  # Add resource processor to explicitly add hostname
  resource:
    attributes:
      # Set a static hostname
      - key: host.name
        value: "my-static-collector-hostname" # <-- CHANGE THIS TO YOUR DESIRED STATIC NAME
        action: upsert # Insert or update the attribute

exporters:
  otlp: 
    endpoint: "ingest.in.signoz.cloud:443"
    tls:
      insecure: false
    headers:
      signoz-ingestion-key: dtsa409InZNwTUjVBS7WPrNLBsANF1ZnZJXd
  debug:
    verbosity: detailed

extensions:
  health_check: {}
  pprof: {}
  zpages: {}

service:
  telemetry:
    logs:
      level: "DEBUG"
      development: true
      encoding: "json"
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp, hostmetrics]
      # Add resource processor before batching
      processors: [resource, batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp, debug] # Only debug exporter 



      