receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  # hostmetrics:
  #   collection_interval: 30s
  #   scrapers:
  #     cpu:
  #     disk:
  #     load:
  #     memory:
  #     network:
  #     filesystem:
  #     paging:
  #     process:
  #     processes:
  # --- Add the docker_stats receiver ---
  docker_stats:
    endpoint: "unix:///var/run/docker.sock" 
    collection_interval: 10s               # How often to scrape metrics
    timeout: 10s
    api_version: "1.47"                     # Specify Docker API version (as string)


processors:
  batch: {}
  # Add resourcedetection processor
  resourcedetection:
    detectors: [env, system, docker]
    override: false # Keep existing attributes if they conflict
  resource:
    attributes:
      # Statically set service.name and host.name for all telemetry
      - key: service.name
        value: "my-static-service"
        action: upsert # Use upsert to ensure it's set
      - key: host.name
        value: "my-static-host"
        action: upsert # Use upsert to ensure it's set
      # Keep existing environment attribute
      - key: deployment.environment
        value: "development"
        action: insert
  # Add filter processor to include only product-service metrics
  filter/include_product_service:
    metrics:
      include:
        match_type: strict
        resource_attributes:
          - key: container.name
            value: product-service

exporters:
  otlp: 
    endpoint: "ingest.in.signoz.cloud:443"
    tls:
      insecure: false
    headers:
      signoz-ingestion-key: dtsa409InZNwTUjVBS7WPrNLBsANF1ZnZJXd
  debug:
    verbosity: detailed

extensions:
  health_check: {}
  pprof: {}
  zpages: {}

service:
  telemetry:
    logs:
      level: "debug" # Set to debug for more verbose collector logs if needed
      # development: true # Consider disabling in production
      encoding: "json"
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, resource, batch] # Add resourcedetection
      exporters: [otlp]
    metrics:
      receivers: [otlp, docker_stats] # Receive OTLP metrics AND docker stats
      processors: [resourcedetection, resource, filter/include_product_service, batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, resource, batch] # Add resourcedetection
      exporters: [otlp] # Send logs to SigNoz




      